apiVersion: v1
kind: Service
metadata:
  name: collector-redis-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
    ports:
    -   port: 6379
        targetPort: 6379
    selector:
        app: redis
        role: master
        tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: collector-redis-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: collector-redis-master
        image: redis:alpine
        resources:
            requests:
                cpu: "10m"
                memory: "100Mi"
            limits:
                cpu: "10m"
                memory: "100Mi"
        ports:
        - containerPort: 6379