apiVersion: v1
kind: Service
metadata:
  name: collector-redis-slave
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  selector:
    app: redis
    role: slave
    tier: backend
  ports:
  - port:  6379
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: collector-redis-slave
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - name: collector-redis-slave
        image: redis:alpine
        resources:
            requests:
                cpu: "10m"
                memory: "100Mi"
            limits:
                cpu: "10m"
                memory: "100Mi"
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 6379