sudo: required
language: node_js
services:
- docker
node_js:
- '6.9'
install:
- npm install
before_script:
- npm run build:prod
script:
- npm run test
after_success:
- npm run coverage
- docker build -f docker/Dockerfile -t "$DOCKER_USERNAME"/"$IMAGE_NAME":"$TRAVIS_BUILD_NUMBER" .
- docker tag "$DOCKER_USERNAME"/"$IMAGE_NAME":"$TRAVIS_BUILD_NUMBER" "$DOCKER_USERNAME"/"$IMAGE_NAME":latest
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push "$DOCKER_USERNAME"/"$IMAGE_NAME":"$TRAVIS_BUILD_NUMBER"
- docker push "$DOCKER_USERNAME"/"$IMAGE_NAME":latest
deploy:
  provider: script
  skip_cleanup: true
  script: kubectl --namespace "$ENV" patch deployment collector-server -p'{"spec":{"template":{"spec":{"containers":[{"name":"collector-server","image":"chinclubi/collector:latest"}]}}}}'
  on:
    all_branches: true
before_install:
- openssl aes-256-cbc -K $encrypted_31c96b1e8904_key -iv $encrypted_31c96b1e8904_iv
  -in deploy-secret.json.enc -out deploy-secret.json -d
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
    export CLOUDSDK_CORE_DISABLE_PROMPTS=1;
    curl https://sdk.cloud.google.com | bash;
  fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud auth activate-service-account --key-file=deploy-secret.json
- gcloud components install kubectl
- gcloud container clusters get-credentials cluster-interact -z asia-east1-a
