sudo: required
language: node_js
services:
  - docker
node_js:
  - '6.9'
install:
  - npm install
before_script:
  - npm run build:prod
script:
  - npm run test
after_success:
  - npm run coverage
before_deploy:
  - docker build -f docker/Dockerfile -t "$DOCKER_USERNAME"/"$IMAGE_NAME":"$TRAVIS_BUILD_NUMBER" .
  - docker tag "$DOCKER_USERNAME"/"$IMAGE_NAME":"$TRAVIS_BUILD_NUMBER" "$DOCKER_USERNAME"/"$IMAGE_NAME":latest
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push "$DOCKER_USERNAME"/"$IMAGE_NAME":"$TRAVIS_BUILD_NUMBER"
  - docker push "$DOCKER_USERNAME"/"$IMAGE_NAME":latest
deploy: 
  provider: gae
  keyfile: deploy-secret.json
  project: theinteract-153915
  on:
      all_branches: true
before_install:
  - openssl aes-256-cbc -K $encrypted_5a9298286e17_key -iv $encrypted_5a9298286e17_iv -in deploy-secret.json.enc -out deploy-secret.json -d
