secret:
    key: SECRET_KEY
    userKey: USER_SECRET_KEY
server:
    protocol: COLLECTOR_PROTOCOL
    host: COLLECTOR_HOST
    port: COLLECTOR_PORT
redis:
    host: REDIS_HOST
    port: REDIS_PORT
mongo:
    protocol: MONGO_PROTOCOL
    host: MONGO_HOST
    port: MONGO_PORT
    auth: MONGO_AUTH