secret:
    key: VSUn0an0eOPd1WFBcaRCvyRmnGjmHE3NxagW3qlVSbFFcltFDTdDjVvWH+N0FPi4X7GdphLx8ACxhVvi9n8H8w==
    userKey: EBsxUzAAAsnaN5c2RTqYqsvTW6ZW4FRwzPKpLkqjD9E5MRFs9rRnFEP27WNkWJKU6grrEAXhvmzDdzstJAPrzLFd
server:
    protocol: http
    host: localhost
    port: 3000
redis:
    host: localhost
    port: 6379
mongo:
    protocol: mongodb
    host: localhost
    port: 27017
    db: interact
    collections:
      names:
        product: product
        user: user
        feature: feature
        version: version
cookie:
    name: collector_uuid
base: 'src/'
