version: '2'
services:
    interact-redis:
        image: redis:alpine
        command:
            - --appendonly
            - "yes"
        ports:
            - 6379:6379
        volumes:
            - redis-data:/data
    interact-mongo:
        container_name: interact-mongo
        image: mongo:latest
        ports:
            - 27018:27017
        volumes:
            - mongo-data:/data
volumes:
    redis-data: {}
    mongo-data: {}