apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: traefik
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  selector:
     matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: traefik
        image: containous/traefik
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        - containerPort: 8080
          name: webadmin
          protocol: TCP
        args:
        - --web
        - --kubernetes
        - --kubernetes.namespaces=production
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-admin
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
  - name: webadmin
    port: 8080
    protocol: TCP
    nodePort: 30001
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
    nodePort: 30000
  type: LoadBalancer