secret:
    key: VSUn0an0eOPd1WFBcaRCvyRmnGjmHE3NxagW3qlVSbFFcltFDTdDjVvWH+N0FPi4X7GdphLx8ACxhVvi9n8H8w==
server:
    protocal: http
    host: localhost
    port: 3000
redis:
    host: localhost
    port: 6379
cookie:
    name: collector_uuid
base: 'src/'