type: object
required:
- API_KEY_PRIVATE
- API_KEY_PUBLIC
- ip
- domainName
properties:
  name:
    type: string
    faker: random.word
  API_KEY_PRIVATE:
    type: string
    faker: random.uuid
  API_KEY_PUBLIC:
    type: string
    faker: random.uuid
  domainName:
    type: string
    faker: internet.url
