type: object
required:
properties:
  productName:
    type: string
    faker: random.word
  API_KEY_PRIVATE:
    type: string
    faker: random.uuid
  API_KEY_PUBLIC:
    type: string
    faker: random.uuid
  ip:
    type: string
    faker: internet.ip
  domainName:
    type: string
    faker: internet.url
